version: '3.3'
services:
  apisix:
    container_name: apisix
    image: apache/apisix:2.10.2-alpine
    restart: always
    volumes:
      - ./config_apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "5445:5445"
      - "5450:5450"
      - "5455:5455"
      - "5460:5460"
      - "11800:11800"
      - "12800:12800"
  spp-platform:
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5107:5107"
    build:
      context: .
      dockerfile: Dockerfile-spp-platform
    environment:
      - SPP_DISABLE_TLS=true
  skywalking-oap:
    container_name: skywalking-oap
    hostname: skywalking-oap
    ports:
      - "5106:5106"
    build:
      context: .
      dockerfile: Dockerfile-skywalking-oap
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5106
      - SPP_DISABLE_TLS=true
  spp-example-webapp:
    container_name: spp-example-webapp
    hostname: spp-example-webapp
    ports:
      - "5105:5105"
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    build:
      context: .
      dockerfile: Dockerfile-spp-example-webapp
    environment:
      - SPP_DISABLE_TLS=true
  skywalking-ui:
    image: apache/skywalking-ui:8.6.0
    container_name: skywalking-ui
    hostname: skywalking-ui
    ports:
      - "8888:8080"
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    environment:
      - SW_OAP_ADDRESS=skywalking-oap:12800
