spp:
  platform_host: "apisix"
  platform_port: 5450
  quiet_mode: false
skywalking:
  logging:
    level: "TRACE"
  agent:
    keep_tracing: true
    is_cache_enhanced_class: true
    class_cache_mode: "FILE"
    service_name: "spp"
  collector:
    backend_service: "apisix:11800"
  plugin:
    toolkit:
      log:
        transmit_formatted: false