spp:
  platform_host: "spp-platform"
  platform_port: 5450
  platform_certificate: |
    MIIFATCCAumgAwIBAgIGAX56wU/vMA0GCSqGSIb3DQEBCwUAMBcxFTATBgNVBAMM
    DHNwcC1wbGF0Zm9ybTAeFw0yMjAxMjEwMzQ5NTZaFw0yMzAxMjEwMzQ5NTZaMBcx
    FTATBgNVBAMMDHNwcC1wbGF0Zm9ybTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
    AgoCggIBAIpbws6+/huSye81bdPJMrZzNkkapabrY+FPPjvEGCxIM0KKwbgnZK44
    vA/tFGzlQFuP/5/6MbuhHSoD6LlvAFigjtiYQuE9PSX3JqgxIVcLOaSwB9gEfYT2
    DzXVCksSysgn54+Ebr95sszpIOvFVU8DZmnUUtrms0VGVxt6K84EGsJls9qC5wA7
    dF7x0onO9BRVFAKQmKCI2NVdcieP7ffcnoPlvLh7OwOGIl2pw9RoRgC9ia7M9BtM
    JdOux7mcMRn8f9N3dekDfwuG09sawauNq48HrQMBN4lWFHMFJP5TVVw97VkEVoNm
    StXD7Ys9LCHuMX3x43II9pYYJxPGB+SjLhKfkbREtou9jX/NLViG37AMNegay8aT
    gAQx/RZZzq3oTM5KEPUrFd3JeM6XCPydtA9wSe5RXRGQm/gkqpSb/TdRadltWbRC
    MlTvOcLKdybm0c2CLBpnlPcPvlC+2x42p3Kt4YXU+FkfQ7wZH0ylj8Fydc6+flBR
    mmoJ+zNKj6iBKb1PyQeV4Y6InP+mPWUdUVMa5lmo4A4GDBdvGmoLJw8dy8tqf1jK
    PpaucfbHrL7NSpN+hpHjFfGrO3EDS91TyZtP7BnndzWdjHwWg78CJawSkHkeu6XG
    iwMxxXKSypU5DpJA/kwJk5ZYoHMm4cRWCq8Cb/4RTK5cZ2GeVJvRAgMBAAGjUzBR
    MB0GA1UdDgQWBBRmntZyLswVMErEM1dWLQIru0JxJTAfBgNVHSMEGDAWgBRmntZy
    LswVMErEM1dWLQIru0JxJTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
    A4ICAQAWvHCPIBZ+4KPtqP/0AT8B9x+iPax6hi17SXVRr9WVQQbKPYETqhOsaGzC
    moCYBIU+g4q1KrRDbW35eXIwYV98DlEK/7mB8Ug+6H1+9b6FhkHVHEoJDq8uuL5M
    VjHzFXYBIXkYf6N4ad+ljidg4h+ZCr5bo2tpgOZtCgPrhAMCvvfHEnj7gCsVg6qT
    BYcanBNPss8u7HbPT1JiUeFO39gklsUg0GiHW5IWl0UV6LEbRmvDEYPYf6c64Tzx
    FKXcn+t9NrwWQeEzmFFRqVqREaVKWqOSKhLus0snh6B/+CK5lPnpJ4Bf8Nc2mpTU
    qy4gRgVB6ZcDXXsEVdN6YyvJDR/Ku/dfAWNg2SaqNKjEI3VWQidCkjyqvLX7VC7p
    HpsYNQ+Ca9PepB0jVIMCv+U8LWI61HGFUs6C4IAPzaKzA77WksXsA/O1O4RTR15N
    hsOOs9GRUihvMP+RfuUwMT2Fqd7eVjFu0ORR+4x/WR1tb8wHdYgL0koQ00AUq7Cf
    kd+eV3TcKjsCcGVVAsMuByHDqwWgyC8Oo0fMlH/L1wPY3VCKMZSTtJTV5HzOQkYo
    d6vx+OCEuKeT0OAX2lx4inzB+k9JsxWU9VHnNUShpI/Xd1k4bqmcj6aDbudhrGlc
    lIOYZqGIYC25yQF1QzTlc5Pai8x1f7n/r4i1laMoylXvOpE3WA==
skywalking:
  logging:
    level: "INFO"
  agent:
    keep_tracing: true
    is_cache_enhanced_class: true
    class_cache_mode: "FILE"
    service_name: "spp"
  collector:
    backend_service: "spp-platform:11800"
  plugin:
    toolkit:
      log:
        transmit_formatted: false